### ISSUE TITLE
Добавить ESLint для typescript

### ISSUE THREAD

**Issue by Kirill02089** [PewPewService/MyNotesBackEnd#3]
### Проблема
Код не однородный, сложно читать

Cледовать гайду
https://tproger.ru/translations/setting-up-eslint-and-prettier/
или
https://robertcooper.me/post/using-eslint-and-prettier-in-a-typescript-project

**Comment by PewPewService** [comment]
добавил eslint, прошелся им по файлам

**Comment by Kirill02089** [comment]
@PewPewService см https://github.com/PewPewService/MyNotesBackEnd/pull/5
